security:
    providers:
        app_users:
            entity:
                class: App\Entity\User
                property: username
    encoders:
        App\Entity\User:
            algorithm: bcrypt
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            http_basic: ~
#            pattern:    ^/
#            http_basic: true
            provider: app_users

            # http_basic: true
            # form_login: true
    access_control:
         - { path: ^/secret, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
